---
title: "Dataviz Assignment 3: Preparation of data"
author: "Ben Chow"
date: "22 October, 2014"
output: html_document
---

### **D, G** ###

** 1. Extraction **

Preliminary code to extract variables from raw csv files downloaded from the WVS website.

```{r, eval = FALSE}
require("plyr")

# Extract from wave 6
x <- read.csv("WVS Wave 6.csv")
y6 <- x[, c("V108", "V148", "V201", "V145", "V25", "V146", "V143", "V147", "V9", "V152", "V2", "V240", "V242", "V248", "V229", "V254", "V144", "V57")]
# US Data only
y6 <- y6[y6$V2==840, ]
y6$V2 <- 3
write.csv(y6, file = "WVS6_rel.csv")
rm(y6)

# Extract from wave 5
load("WVS Wave 5.rdata")
x <- WV5_Data_spss_v_2014_04_28
rm(WV5_Data_spss_v_2014_04_28)
y5 <- x[, c("V192", "V200", "V186", "V193", "V187", "V9", "V2", "V235", "V237", "V238", "V241", "V256", "V185", "V55", "V131", "V194", "V197", "V196", "V58", "V24", "V184")]
y5 <- y5[y5$V2==840, ]
y5$V2 <- 2
write.csv(y5, file = "WVS5_rel.csv")
rm(y5)

# Extract from wave 4
load("WVS Wave 4.rdata")
x <- get("WV4_Data_rdata_v_2014-04-28", envir = globalenv())
y4 <- x[, c("v196", "v206", "v185", "v198", "v186", "v9", "v2", "v223", "v225", "v226", "v229", "V242", "v184", "v106", "v147", "v200", "v203", "v202", "v193", "v195", "v191", "v111", "v40", "v182")]
y4 <- rename(y4, c("V242" = "v242"))
y4 <- y4[y4$v2==840,]
y4$v2 <- 1
write.csv(y4, file = "WVS4_rel.csv")
rm(list=ls())
```

Final product: 3 csv files with each of the corresponding 3 waves, with only the relevant variables, and only observations from the USA. v2 / V2 now corresponds to the wave number.

** 2. Renaming **

```{r, eval = FALSE}
W6 <- y6
W5 <- y5
W4 <- y4

# Key variables (including demographic)
W6 <- rename(W6, c("V152" = "prvblf", "V201" = "othblf", "V145" = "pubact", "V146" = "prvact", "V147" = "iden1", "V9" = "iden2", "V2" = "wave", "V240" = "sex", "V242" = "age", "V248" = "educ", "V229" = "work", "V254" = "ethnic", "V144" = "denom", "V57" = "marital"))

W5 <- rename(W5, c("V192" = "prvblf", "V200" = "othblf", "V186" = "pubact", "V193" = "prvact", "V187" = "iden1", "V9" = "iden2", "V2" = "wave", "V235" = "sex", "V237" = "age", "V238" = "educ", "V241" = "work", "V256" = "ethnic", "V185" = "denom", "V55" = "marital"))

W4 <- rename(W4, c("v196" = "prvblf", "v206" = "othblf", "v185" = "pubact", "v198" = "prvact", "v186" = "iden1", "v9" = "iden2", "v2" = "wave", "v223" = "sex", "v225" = "age", "v226" = "educ", "v229" = "work", "v242" = "ethnic", "v184" = "denom", "v106" = "marital"))

# Residual vars
W6 <- rename(W6, c("V108" = "pubblf1", "V148" = "prvblf4", "V25" = "pubact3", "V143" = "prvact2"))
W5 <- rename(W5, c("V131" = "pubblf1", "V194" = "pubblf2", "V197" = "pubblf3", "V196" = "pubblf4", "V58" = "othblf2", "V24" = "pubact3", "V184" = "prvact2"))
W4 <- rename(W4, c("v147" = "pubblf1", "v200" = "pubblf2", "v203" = "pubblf3", "v202" = "pubblf4", "v193" = "prvblf2", "v195" = "prvblf3", "v191" = "prvblf4", "v111" = "othblf2", "v40" = "pubact2", "v182" = "prvact2"))
```

** 3. Recoding **
```{r, eval = FALSE}
require("plyr")
# Recode for prvact: Do you pray every once in awhile? 0: No. 1: Yes
W6$prvact <- recodeVar(W6$prvact, src = c(1:8), tgt = c(rep(1, 4), rep(0, 4)))
W5$prvact <- recodeVar(W5$prvact, src = c(-5, -2, 1, 2), tgt = c(NA, NA, 1, 0))
W4$prvact <- recodeVar(W4$prvact, src = c(-1, 1, 2), tgt = c(NA, 1, 0))

# Recode for ethnic
W6$ethnic <- recodeVar(W6$ethnic, src = c(840002:840006), tgt = c("White", "Black", "Other", "Hispanic", "Other"))
W6$ethnic <- factor(W6$ethnic, levels = c("White", "Black", "Hispanic", "Other"))
W5$ethnic <- recodeVar(W5$ethnic, src = c(1400, 200, 1250, 8001, 8000), tgt = c("White", "Black", "Hispanic", "Other", "Other"))
W5$ethnic <- factor(W5$ethnic, levels = c("White", "Black", "Hispanic", "Other"))
W4$ethnic <- recodeVar(W4$ethnic, src = c(840002:840009), tgt = c("White", "Black", "Other", "Hispanic", NA, rep("Other", 3)))
W4$ethnic <- factor(W4$ethnic, levels = c("White", "Black", "Hispanic", "Other"))

# Recode for marital
W6$marital <- recodeVar(W6$marital, src = c(1:6), tgt = c("Married", "Married", "Separated", "Separated", "Widowed", "Single"))
W6$marital <- factor(W6$marital)
W5$marital <- recodeVar(W5$marital, src = c(1:6), tgt = c("Married", NA, "Separated", "Separated", "Widowed", "Single"))
W5$marital <- factor(W5$marital)
W4$marital <- recodeVar(W4$marital, src = c(1:6), tgt = c("Married", "Married", "Separated", "Separated", "Widowed", "Single"))
W4$marital <- factor(W4$marital)

# Recode for work
W6$work <- recodeVar(W6$work, src = c(1:8), tgt = c("Full Time", "Part Time", "Self Employed", "Unemployed", "Housewife", "Other", "Unemployed", "Other"))
W6$work <- factor(W6$work, levels = c("Full Time", "Part Time", "Self Employed", "Housewife", "Unemployed", "Other"))
W5$work <- recodeVar(W5$work, src = c(1:8), tgt = c("Full Time", "Part Time", "Self Employed", "Unemployed", "Housewife", "Other", "Unemployed", "Other"))
W5$work <- factor(W5$work, levels = c("Full Time", "Part Time", "Self Employed", "Housewife", "Unemployed", "Other"))
W4$work <- recodeVar(W4$work, src = c(-1, 1:8), tgt = c(NA, "Full Time", "Part Time", "Self Employed", "Unemployed", "Housewife", "Other", "Unemployed", "Other"))
W4$work <- factor(W4$work, levels = c("Full Time", "Part Time", "Self Employed", "Housewife", "Unemployed", "Other"))

# Recode for educ
W6$educ <- recodeVar(W6$educ, src = c(1:9), tgt = c(rep("Primary School", 3), rep("High School", 4), "Some College", "Degree"))
W6$educ <- ordered(W6$educ, levels = c("Primary School", "High School", "Some College", "Degree"))
W5$educ <- recodeVar(W5$educ, src = c(1:9), tgt = c(rep("Primary School", 3), rep("High School", 4), "Some College", "Degree"))
W5$educ <- ordered(W5$educ, levels = c("Primary School", "High School", "Some College", "Degree"))
W4$educ <- recodeVar(W4$educ, src = c(1:9), tgt = c(rep("Primary School", 3), rep("High School", 4), "Some College", "Degree"))
W4$educ <- ordered(W4$educ, levels = c("Primary School", "High School", "Some College", "Degree"))

# Recode for gender
W6$sex <- recodeVar(W6$sex, src = c(1, 2), tgt = c("Male", "Female"))
W6$sex <- factor(W6$sex)
W5$sex <- recodeVar(W5$sex, src = c(1, 2), tgt = c("Male", "Female"))
W5$sex <- factor(W5$sex)
    table(W4$sex)
W4$sex <- recodeVar(W4$sex, src = c(1, 2), tgt = c("Male", "Female"))
W4$sex <- factor(W4$sex)

# Recode for denom
    table(W6$denom)
W6$denom <- recodeVar(W6$denom, src = c(0, 12, 31, 42, 49, 52, 53, 62, 64), tgt = c("None", "Other", "Other", "Judaism", "Other", "Christian", "Other", "Christian", "Catholic"))
W6$denom <- factor(W6$denom, levels = c("None", "Christian", "Catholic", "Judaism", "Other"))
    table(W5$denom)
W5$denom <- recodeVar(W5$denom, src = c(-5, -2, 0, 12, 31, 42, 49, 52, 53, 62, 64), tgt = c(NA, NA, "None", "Other", "Other", "Judaism", "Other", "Christian", "Other", "Christian", "Catholic"))
W5$denom <- factor(W5$denom, levels = c("None", "Christian", "Catholic", "Judaism", "Other"))
    table(W4$denom)
W4$denom <- recodeVar(W4$denom, src = c(-2, 0, 12, 31, 42, 49, 52, 53, 62, 64), tgt = c(NA, "None", "Other", "Other", "Judaism", "Other", "Christian", "Other", "Christian", "Catholic"))
W4$denom <- factor(W4$denom, levels = c("None", "Christian", "Catholic", "Judaism", "Other"))
```

** 4. Merging Datasets **

```{r, eval = FALSE}
require(plyr)
W45 <- join(W4, W5, type = "full")
wvs <- join(W45, W6, type = "full")
str(wvs)
write.csv(wvs, file = "WVS456_rel.csv")
```

** 5. More recoding in merged dataset **

```{r, eval = FALSE}
# prvblf: How important is God in your life [0:9]
wvs$prvblf <- recodeVar(wvs$prvblf, src = c(1:10), tgt = c(0:9))

# othblf: How often is cheating on taxes justified (if you have a chance)? [0:9]
wvs$othblf <- 10 - wvs$othblf

# pubact: How often do you attend religious services these days (apart from weddings and funerals)? [0:6]
wvs$pubact <- recodeVar(wvs$pubact, src = c(-1, -2, -5, 1:7), tgt = c(NA, NA, NA, 6:0))

# prvact: Do you take some moments of prayer and meditation from time to time? [0:1]

# iden1: Independently of religious service attendance, would you consider yourself religious? [0:2]
wvs$iden1 <- recodeVar(wvs$iden1, src = c(-5, -2, -1, 1:3), tgt = c(NA, NA, NA, 2:0))

# iden2: How important is religion in your life? [0:3]
wvs$iden2 <- recodeVar(wvs$iden2, src = c(-2, -1, 1:4), tgt = c(NA, NA, 3:0))

# Wave variable
wvs$wave <- factor(wvs$wave)

# Exclude nonreligious respondents
wvs <- wvs[wvs$denom!="None", ]
wvs <- wvs[!is.na(wvs$denom), ]

# Overwrite file
write.csv(wvs, file = "WVS456_rel.csv")
```



