---
title: "2014-09-18-fchen-hw1"
author: "fchen"
date: "Thursday, September 11, 2014"
output: html_document
published: false
tags: hw1
---

## Loading bboying injury data
```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA}
setwd("/Users/knarf/Copy/Datasets/bboy")
k1 <- read.table("kauther_t1.txt") 
k2 <- read.table("kauther_t2.txt") 
k3 <- read.table("kauther_t3.txt") 
k4 <- read.table("kauther_t4.txt") 
k5 <- read.table("kauther_t5.txt")
```

# Kauther's first table

```{r, echo = FALSE, warning = FALSE, message = FALSE}
height <- rbind(k1$amateur_mean, k1$prof_mean)
colnames(height) <- c("age", "bmi", "yr_dance", "hr/week_train", "min_warmup", "min_stretch", "headspin_train", "yr_headspin", "% use trainer", "doc-visit/person")
bar1 <- barplot(height, names.arg = colnames(height),
        main = "Professional vs. Amateur Bboys (Average Characteristics)", 
        xlab = "Mean Values (multiple)", 
        cex.names = 0.6, 
        cex.axis = 0.6, 
        las = 2, 
        xlim = c(0,80), 
        horiz = TRUE,
        width = 3,
        beside = TRUE,
        legend = TRUE
        )
text(height, bar1, label = height, pos = 4, cex = 0.65, col = "red")
```

## Kauther's second table

```{r, echo = FALSE, warning = FALSE, message = FALSE}
height2 <- rbind(k2$amateurs, k2$professionals)
colnames(height2) <- c("# of Injuries", "Injuries/bboy", "Hours/Injury", "# OVS", "OVS/bboy", "Hours/OVS")
bar2 <- barplot(height2, names.arg = colnames(height2), 
        main = "Professional vs. Amateur Bboys (Injuries & Overuse Syndrome (OVS))", 
        xlab = "Mean Values", 
        cex.names = 0.6, 
        cex.axis = 0.6, 
        las = 2, 
        xlim = c(0,2500), 
        horiz = TRUE,
        width = 3,
        beside = TRUE, 
        legend = TRUE,
        args.legend = list(x = "bottomright")
        )
text(height2, bar2, label = height2, pos = 4, cex = 0.65, col = "red")
```

# Kauther's third table

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library("lattice")
xyplot(k3$proff ~ k3$ama, groups = rownames(k3),
      ylim = c(0, 250),
      ylab = "Professional Injuries Count",
      xlim = c(0, 250),
      xlab = "Amateur Injuries Count",
      abline = c(0, 1),
      main = "Injuries Count by Region",
panel = function(x, y) {
      panel.xyplot(x, y, abline = c(0, 1), subscripts = TRUE, 
      groups = rownames(k3))
      ltext(x = k3$ama, y = k3$proff, labels = rownames(k3),
      pos = 4, cex = 0.8)
      })
      
xyplot(k3$proff_inj_pp ~ k3$ama_inj_pp, groups = rownames(k3),
       ylim = c(0, 4),
       ylab = "Professional Injuries per Person",
       xlim = c(0, 4),
       xlab = "Amateur Injuries per Person",
       abline = c(0, 1),
       main = "Injuries per Person by Region",
panel = function(x, y) {
      panel.xyplot(x, y, abline = c(0, 1), subscripts = TRUE, 
      groups = rownames(k3))
      ltext(x = k3$ama_inj_pp, y = k3$proff_inj_pp, 
      labels = rownames(k3), pos = 4, cex = 0.8)
      })
```

## Kauther's fourth table

```{r, echo = FALSE, warning = FALSE, message = FALSE}
bar5lab <- c("Rare", "Seldom", "Often", "Very Often")
par(mfrow = c(1, 2))
bar5 <- barplot(k4$amateur, names.arg = rownames(k4),
        main = "Amateur Gear Usage",
        xlab = "Type of Gear", 
        cex.names = 0.6, 
        cex.axis = 0.6, 
        las = 1, 
        ylim = c(0,4), 
        horiz = FALSE,
        width = 1,
        yaxt = "n"
        )
axis(2, at = 1:4, labels = bar5lab, tick = FALSE, las = 2, cex.axis = 0.6)
# text(bar5, amateur, label = amateur, pos = 3, cex = 0.80, col = "red")

bar6 <- barplot(k4$professional, names.arg = rownames(k4),
        main = "Professional Gear Usage", 
        xlab = "Type of Gear", 
        cex.names = 0.6, 
        cex.axis = 0.6, 
        las = 1, 
        ylim = c(0,4), 
        horiz = FALSE,
        width = 1,
        yaxt = "n"
        )
axis(2, at = 1:4, labels = bar5lab, tick = FALSE, las = 2, cex.axis = 0.6)
# text(bar6, professional, label = professional, pos = 3, cex = 0.80, col = "red")
```

## Kauther's fifth table

```{r, echo = FALSE, warning = FALSE, message = FALSE}
k5s <- k5[-1,]
xyplot(k5s$td_loss ~ k5s$td_loss_overuse, groups = rownames(k5s),
       ylim = c(0, 4200),
       ylab = "Total Loss of Training Days",
       xlim = c(0, 15),
       xlab = "Loss of Training Days per Injury",
       main = "Loss of Training Days (Totals & per Injury)",
panel = function(x, y) {
      panel.xyplot(x, y, abline = c(0, 1), subscripts = TRUE, 
      groups = rownames(k5s))
      ltext(x = k5s$td_loss_overuse, y = k5s$td_loss, 
      labels = rownames(k5s), pos = 4, cex = 1)
      })
```

# Playing around with ggvis, using the cocaine dataset

```{r}
library("dplyr")
library("ggvis")
head(cocaine)
tail(cocaine)

cocaine %>%
    ggvis(x = ~weight, y = ~price, fill := "green")
    layer_points()

cocaine %>% ggvis(~weight) %>%
    layer_histograms(binwidth = 5)

state <- as.vector(unique(cocaine$state))
cocaine %>%
      ggvis(~potency) %>%
        filter(state == eval(input_select(
        choices = state,
        selected = "NY",
        label = "State"))) %>%
      layer_histograms(binwidth = 2)
```

