---
title: "hw1"
author: "Lanxiang Li"
date: "September 17, 2014"
output: html_document
published: false
tags: hw1
---
# hw1
## Lanxiang_Li-caroline

### 1. read data

```{r}
setwd("~/Desktop/qmssviz/Lab1")
dd <- read.csv("Donation-Disease.csv")
```

### 2. draw charts

#### scatter diagram
```{r}
library(ggplot2)
qplot(x = Name, y = Death, data = dd, color = Name)
```
```{r}
library(ggplot2)
qplot(x = Name, y = MoneyRaised, data = dd, color = Name)
```
```{r}
library(ggplot2)
p <- ggplot(data = dd, mapping = aes(x = Death, y = MoneyRaised))
p + geom_point()
```
```{r}
library(ggplot2)
ggplot(dd, aes(x=Death, y=MoneyRaised)) +
geom_point(shape=1)
```
```{r}
library(ggplot2)
ggplot(dd, aes(x=Death, y=MoneyRaised)) +
geom_point (shape=1) +
geom_smooth(method=lm)
```
#### pie chart
```{r}
library(ggplot2)
par(mar=c(8,8,8,8),font=4)
pct <- round (dd$MoneyRaised/sum(dd$MoneyRaised)*100)
lbls<- paste(dd$Name, " ",pct, "%", sep="")
pie(dd$MoneyRaised, labels=lbls,col=rainbow(length(lbls)), main="pie chart of MoneyRaised")
```
```{r}
library(ggplot2)
par(mar=c(8,8,8,8),font=4)
pct <- round (dd$Death/sum(dd$Death)*100)
lbls<- paste(dd$Name, " ",pct, "%", sep="")
pie(dd$Death, labels=lbls,col=rainbow(length(lbls)), main="pie chart of Death")
```

